### ISSUE TITLE
WebAssembly SDK

### ISSUE THREAD

**Issue by ciaoamigoschat** [quasipaa/Spinosa#35]
News?

**Comment by quasipaa** [comment]
> News?

The current idea is to pre-process audio and video data through WebAssembly.

**Comment by ciaoamigoschat** [comment]
Is there any sdk to try? I like your project. Do you have any estimates for the end?

**Comment by quasipaa** [comment]
> Is there any sdk to try? I like your project. Do you have any estimates for the end?

I am currently completing support for a standalone WebRTC server. This project is an arduous task, and I am the only one who has completed this project. I don't have much free time, so the progress is relatively slow. After thinking about it for a while, I decided to focus on WebRTC and make it a mature WebRTC streaming server. The complex plan prepared in the early stage slowed my pace, so I will shift the focus to focus on a certain problem, I will organize the current modules and gradually capture each castle

**Comment by ciaoamigoschat** [comment]
With a sposor I can speed up the process

**Comment by quasipaa** [comment]
> With a sposor I can speed up the process

Thank you for your kindness, I have other jobs, my profession is a tech leader, so my spare time is precious and scarce for me.
